name: CI

on:
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Did you test?
        run: |
          echo "Checking if PR changes are on test branch"
          git status
          git branch
          git log --pretty=‘%h’ staging..test

          
