name: CI

on:
  pull_request:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Did you test?
        run: |
          echo "Checking if PR changes are on test branch"

          HASH=$(git log -2 --pretty=‘%h’ | sed -e "s/^‘//" -e "s/’$//")
          echo $HASH
          git branch --contains $HASH

          
