name: CI

on:
  pull_request:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Did you test?
        run: |
          echo "Checking if PR changes are on test branch"
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
          git checkout test
          git checkout -
          HASH=$(git log --pretty=‘%h’| sed -n '2 p' | sed -e "s/^‘//" -e "s/’$//")
          echo $HASH
          if echo $(git branch --contains $HASH) | grep -w 'test'; then
            echo "The feature is already merged on testing environment [ OK ]"
          else
            echo "The feature is not merged on testing environment [ ERROR ]"
            exit 1
          fi
